"""empty message

Revision ID: 5a2d2c14c089
Revises: 52cd634aa3c5
Create Date: 2018-01-12 17:25:30.057718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2d2c14c089'
down_revision = '52cd634aa3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classy_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('s3bucket', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classy_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('classication_label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classication_label_id'], ['classy_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classy_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=1000), nullable=True),
    sa.Column('file_created', sa.DateTime(), nullable=True),
    sa.Column('classification_text', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('classication_label_id', sa.Integer(), nullable=True),
    sa.Column('classy_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classication_label_id'], ['classy_label.id'], ),
    sa.ForeignKeyConstraint(['classy_job_id'], ['classy_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classy_text')
    op.drop_table('classy_label')
    op.drop_table('classy_job')
    # ### end Alembic commands ###
